#!/usr/bin/env bash
# Rebuilds the TurboWarp scratch-gui editor from tools/scratchedit-src/
# and copies the production output into tools/scratchedit/, which is
# the folder actually served at andy-and-terry.github.io/tools/scratchedit/.
#
# Usage (from anywhere in the repo):
#   tools/scratchedit-src/build-and-deploy.sh
#
# Requirements: Node.js + npm.

set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SRC_DIR/../.." && pwd)"
DEPLOY_DIR="$REPO_ROOT/tools/scratchedit"

cd "$SRC_DIR"

if [ ! -d node_modules ]; then
    echo "Installing dependencies..."
    npm install --ignore-scripts
fi

# The upstream "prepublish" script downloads a micro:bit hex file used only
# by the micro:bit hardware extension's packager. It requires network access
# to packagerdata.turbowarp.org. Run it if the generated file is missing;
# if it fails (e.g. no network access to that host), fall back to a
# placeholder so the rest of the editor still builds. Skip entirely if
# already generated by a previous run.
if [ ! -f src/generated/microbit-hex-url.cjs ]; then
    echo "Generating micro:bit hex asset..."
    if ! node scripts/prepublish.mjs; then
        echo "Warning: could not download the real micro:bit hex file (no network access?)." >&2
        echo "Falling back to a placeholder — the micro:bit hex export feature will not work." >&2
        mkdir -p src/generated static/microbit
        printf ':020000040000FA\n:00000001FF\n' > static/microbit/scratch-microbit-1.2.0.hex
        cat > src/generated/microbit-hex-url.cjs << 'EOF'
// This file is generated by build-and-deploy.sh as a fallback because
// scripts/prepublish.mjs could not download the real micro:bit hex file.
module.exports = require('../../static/microbit/scratch-microbit-1.2.0.hex');
EOF
    fi
fi

echo "Building production bundle..."
NODE_ENV=production npm run build

echo "Deploying build output to $DEPLOY_DIR ..."
rm -rf "$DEPLOY_DIR"
mkdir -p "$DEPLOY_DIR"
cp -r build/. "$DEPLOY_DIR/"

echo "Done. Deployed to tools/scratchedit/"
